# Generated by Django 5.1.4 on 2025-01-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_title', models.TextField(max_length=30, verbose_name='Заголовок таблицы')),
                ('competency_table', models.TextField(verbose_name='Таблица компетенций')),
                ('skills_chart', models.ImageField(upload_to='uploads/images/%Y/%m/%d', verbose_name='Диаграмма ключевых навыков')),
            ],
        ),
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание основной информации')),
                ('image', models.ImageField(upload_to='uploads/images/%Y/%m/%d', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='MarketTrends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_trend_chart', models.ImageField(upload_to='uploads/images/%Y/%m/%d', verbose_name='Диаграмма изменения зарплат')),
                ('vacancy_trend_chart', models.ImageField(upload_to='uploads/images/%Y/%m/%d', verbose_name='Диаграмма изменения вакансий')),
                ('trend_table', models.TextField(verbose_name='Сводная таблица тенденций')),
            ],
        ),
        migrations.CreateModel(
            name='RecentJobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100, verbose_name='Название вакансии')),
                ('target_vacancy', models.TextField(verbose_name='Целевая вакансия для анализа')),
            ],
        ),
        migrations.CreateModel(
            name='RegionalStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_salary_chart', models.ImageField(upload_to='uploads/images/%Y/%m/%d', verbose_name='Диаграмма зарплат по регионам')),
                ('city_vacancy_share_chart', models.ImageField(upload_to='uploads/images/%Y/%m/%d', verbose_name='Диаграмма доли вакансий по регионам')),
                ('regional_table', models.TextField(verbose_name='Таблица региональной статистики')),
            ],
        ),
    ]
