# Generated by Django 5.0.3 on 2025-01-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_chart', models.ImageField(upload_to='uploads/demand/%Y/%m/%d', verbose_name='График зарплат по годам')),
                ('vacancy_chart', models.ImageField(upload_to='uploads/demand/%Y/%m/%d', verbose_name='График вакансий по годам')),
                ('demand_table', models.TextField(verbose_name='Таблица востребованности')),
            ],
        ),
        migrations.CreateModel(
            name='GeographyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_salary_chart', models.ImageField(upload_to='uploads/geography/%Y/%m/%d', verbose_name='График зарплат по городам')),
                ('city_vacancy_chart', models.ImageField(upload_to='uploads/geography/%Y/%m/%d', verbose_name='График вакансий по городам')),
                ('geography_table', models.TextField(verbose_name='Таблица географии')),
            ],
        ),
        migrations.CreateModel(
            name='MainPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание профессии')),
                ('image', models.ImageField(upload_to='uploads/main_page/%Y/%m/%d', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='RecentVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('vacancy_query', models.TextField(verbose_name='Запрос для поиска вакансий')),
            ],
        ),
        migrations.CreateModel(
            name='SkillsetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_title', models.CharField(max_length=50, verbose_name='Название таблицы')),
                ('skills_table', models.TextField(verbose_name='Таблица навыков')),
                ('skills_chart', models.ImageField(upload_to='uploads/skills/%Y/%m/%d', verbose_name='График навыков')),
            ],
        ),
        migrations.DeleteModel(
            name='CompetencyAnalytics',
        ),
        migrations.DeleteModel(
            name='LandingPageContent',
        ),
        migrations.DeleteModel(
            name='MarketTrends',
        ),
        migrations.DeleteModel(
            name='RecentJobListing',
        ),
        migrations.DeleteModel(
            name='RegionalStatistics',
        ),
    ]
